name: geo-clip
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0
  - asttokens=2.0.5
  - attrs=23.1.0
  - aws-c-auth=0.7.16
  - aws-c-cal=0.6.10
  - aws-c-common=0.9.14
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.6
  - aws-c-mqtt=0.10.3
  - aws-c-s3=0.5.5
  - aws-c-sdkutils=0.1.15
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.4
  - aws-sdk-cpp=1.11.267
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.7
  - branca=0.6.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - cfitsio=3.470
  - charset-normalizer=2.0.4
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - cuda-cccl=12.4.99
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.4.99
  - cuda-runtime=11.8.0
  - curl=8.7.1
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.5.0
  - filelock=3.13.1
  - fiona=1.8.22
  - folium=0.14.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - freexl=1.0.6
  - fsspec=2024.3.1
  - geopandas=0.12.2
  - geopandas-base=0.12.2
  - geos=3.8.0
  - geotiff=1.7.0
  - gettext=0.19.8.1
  - glib=2.72.1
  - glib-tools=2.72.1
  - gmpy2=2.1.2
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.1
  - intel-openmp=2023.1.0
  - ipykernel=6.28.0
  - ipython=8.15.0
  - jedi=0.18.1
  - jinja2=3.1.3
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - kealib=1.4.14
  - kiwisolver=1.4.4
  - krb5=1.21.2
  - lerc=3.0
  - libabseil=20240116.1
  - libarrow=15.0.2
  - libarrow-acero=15.0.2
  - libarrow-dataset=15.0.2
  - libarrow-flight=15.0.2
  - libarrow-flight-sql=15.0.2
  - libarrow-gandiva=15.0.2
  - libarrow-substrait=15.0.2
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libclang=12.0.1
  - libclang13=14.0.6
  - libcrc32c=1.1.2
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.5.119
  - libcurand-dev=10.3.5.119
  - libcurl=8.7.1
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libevent=2.1.12
  - libffi=3.4.2
  - libgdal=3.0.2
  - libglib=2.72.1
  - libgoogle-cloud=2.22.0
  - libgoogle-cloud-storage=2.22.0
  - libgrpc=1.62.1
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libnetcdf=4.8.1
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libogg=1.3.4
  - libparquet=15.0.2
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.5.1
  - libutf8proc=2.8.0
  - libuv=1.44.2
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libzip=1.8.0
  - libzlib=1.2.13
  - lightning=2.2.1
  - lightning-utilities=0.11.2
  - llvmlite=0.42.0
  - lz4-c=1.9.4
  - m2w64-expat=2.1.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-libiconv=1.14
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-xz=5.2.2
  - mapclassify=2.5.0
  - markupsafe=2.1.3
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - munch=2.5.0
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - networkx=3.1
  - numba=0.59.1
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.2.1
  - orc=2.0.0
  - packaging=23.2
  - pandas=2.2.1
  - parso=0.8.3
  - pcre=8.45
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.3.1
  - platformdirs=3.10.0
  - ply=3.11
  - proj=6.2.1
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pyarrow=15.0.2
  - pygments=2.15.1
  - pyparsing=3.0.9
  - pyproj=2.6.1.post1
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.9.19
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytorch=2.2.2
  - pytorch-cuda=11.8
  - pytorch-lightning=2.2.1
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pywin32=305
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - rasterio=1.2.10
  - re2=2023.09.01
  - requests=2.31.0
  - rtree=1.0.1
  - scikit-learn=1.3.0
  - scipy=1.12.0
  - setuptools=68.2.2
  - shapely=2.0.1
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.10
  - snuggs=1.4.7
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.12
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tiledb=2.3.3
  - tomli=2.0.1
  - torchmetrics=1.3.2
  - tornado=6.3.3
  - tqdm=4.66.2
  - traitlets=5.7.1
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - urllib3=2.1.0
  - vc=14.2
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wcwidth=0.2.5
  - wheel=0.41.2
  - win_inet_pton=1.1.0
  - xerces-c=3.2.4
  - xyzservices=2022.9.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - exifread==3.0.0
      - gdal==3.0.2
      - geographiclib==2.0
      - geopy==2.4.1
      - grpcio==1.62.1
      - huggingface-hub==0.22.2
      - markdown==3.6
      - protobuf==5.26.1
      - regex==2023.12.25
      - safetensors==0.4.2
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tokenizers==0.15.2
      - torchaudio==2.2.2
      - torchvision==0.17.2
      - transformers==4.39.3
      - werkzeug==3.0.2
      - yacs==0.1.8
